### ISSUE TITLE
Values of mdns response have a false representation

### ISSUE THREAD

**Issue by deimi** [KiraleTech/KiBRA#8]
The mdns response values for `sb`, `xp`, `sq` and `bb` are false encoded. Instead of a string representation of hex values, they are transmitted as raw byte values.

I'm using Kibra v2.1.0

See attached wireshark screenshot and trace
[false_mdsn_encoding.pcapng.zip](https://github.com/KiraleTech/KiBRA/files/4551588/false_mdsn_encoding.pcapng.zip)
![image](https://user-images.githubusercontent.com/8256985/80594982-46d45e00-8a24-11ea-8838-ce2903b976f4.png)

**Comment by KiraleDev** [comment]
Hi @deimi,
Thread Specification defines some fields, within mDNS response, whose value is binary-encoded, such as those you correctly pointed out.

**Comment by deimi** [comment]
Oh sorry, I didn't know this. Should have read the specification :sweat_smile: 
In this case the other side (ot-commissioner) I'm using has a bug.
